# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49b2a0f66f42b460568c635753da4cd9fe604ca9381c17be8b5ce1d9ce3067bf927ea68528fc56c3aaa979b1aa4db2108c08f8470fde701bf97ee46358f9c0c6

test:
  secret_key_base: 1c6471545e7575ffd745eb7be078c10d41d23ca249ad83e20b38dba51db755c101ee2fdb5d938876b28053ec95436479dfc872d0cc515369b2737b57d315136b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
